// Angular build information, automatically generated by `generate-build-infos` script
export const buildInfo = {
  hash: '<hash>',
  user: '<user>',
  jenkinsBuildId: '<BUILD_ID>',
  timestamp: '<timestamp>'
};
